-- =============================================================================
-- DEPRECATED — use 005_study_room_ssot_align.sql (SSOT 5장)
-- =============================================================================
-- This file is kept for history only. Do not apply after 005.
