name: Deploy to dothome

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: "112.175.184.80"
          username: "study114"
          password: $ secrets.FTP_PASSWORD 
          server-dir: "/hosting/study114/html/"